<?php

# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT IT DIRECTLY.

$path = __DIR__ . '/../storage/';

if (isset($_GET['code'])) {
    if (! is_dir($path)) {
        mkdir($path, 0755, true);
    }

    if (file_put_contents($path . 'token', $_GET['code'])) {
        die('TOKEN SAVED. YOU CAN CLOSE THIS WINDOW NOW.');
    }

    die('UNABLE TO SAVE TOKEN.');
}
